In [25]:
import numpy as np
import pandas as pd

In [26]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [27]:
df = pd.read_csv('covid_toy.csv')


In [28]:
df

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No
...,...,...,...,...,...,...
95,12,Female,104.0,Mild,Bangalore,No
96,51,Female,101.0,Strong,Kolkata,Yes
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No


In [29]:
df.isnull().sum()


age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [31]:
X_train


,age,gender,fever,cough,city
56,71,Male,NaN,Strong,Kolkata
73,34,Male,98.0,Strong,Kolkata
55,81,Female,101.0,Mild,Mumbai
80,14,Female,99.0,Mild,Mumbai
16,69,Female,103.0,Mild,Kolkata
...,...,...,...,...,...
9,64,Female,101.0,Mild,Delhi
6,14,Male,101.0,Strong,Bangalore
15,70,Male,103.0,Strong,Kolkata
26,19,Female,100.0,Mild,Kolkata


# Simple

In [32]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever

array([[100.68055556],
       [ 98.        ],
       [101.        ],
       [ 99.        ],
       [103.        ],
       [100.        ],
       [104.        ],
       [100.68055556],
       [102.        ],
       [102.        ],
       [ 98.        ],
       [104.        ],
       [100.        ],
       [ 99.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [100.68055556],
       [102.        ],
       [100.        ],
       [101.        ],
       [102.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [ 99.        ],
       [ 98.        ],
       [104.        ],
       [103.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [100.68055556],
       [104.        ],
       [100.68055556],
       [100.68055556],
       [100.        ],
       [100.68055556],
       [ 98

In [33]:
# Ordinal encoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],

In [34]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city

array([[1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],


In [35]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age

array([[71],
       [34],
       [81],
       [14],
       [69],
       [10],
       [54],
       [82],
       [49],
       [69],
       [80],
       [25],
       [47],
       [65],
       [40],
       [12],
       [13],
       [83],
       [55],
       [68],
       [50],
       [81],
       [42],
       [64],
       [27],
       [47],
       [24],
       [ 5],
       [26],
       [23],
       [49],
       [ 5],
       [12],
       [60],
       [56],
       [69],
       [ 6],
       [23],
       [16],
       [75],
       [34],
       [27],
       [20],
       [65],
       [18],
       [65],
       [33],
       [20],
       [38],
       [73],
       [51],
       [64],
       [74],
       [15],
       [72],
       [82],
       [83],
       [16],
       [31],
       [65],
       [46],
       [59],
       [75],
       [71],
       [42],
       [51],
       [11],
       [19],
       [10],
       [25],
       [79],
       [20],
       [11],
       [80],
       [27],
       [64],
       [14],

In [36]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed

array([[ 71.        , 100.68055556,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 34.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 81.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 14.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 69.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 10.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 54.        , 104.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 82.        , 100.68055556,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 49.        , 102.        ,   0.        ,   1.        ,
          0.    

# Efficient

In [37]:
from sklearn.compose import ColumnTransformer


In [38]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [39]:
X_transformed = transformer.fit_transform(X_train)

In [42]:
transformed_columns = (
    ['fever'] + 
    ['cough_encoded'] + 
    transformer.named_transformers_['tnf3'].get_feature_names_out(['gender', 'city']).tolist() + 
    ['age']
)

df_transformed = pd.DataFrame(X_transformed, columns=transformed_columns)
df_transformed

,fever,cough_encoded,gender_Male,city_Delhi,city_Kolkata,city_Mumbai,age
0,100.680556,1.0,1.0,0.0,1.0,0.0,71.0
1,98.000000,1.0,1.0,0.0,1.0,0.0,34.0
2,101.000000,0.0,0.0,0.0,0.0,1.0,81.0
3,99.000000,0.0,0.0,0.0,0.0,1.0,14.0
4,103.000000,0.0,0.0,0.0,1.0,0.0,69.0
...,...,...,...,...,...,...,...
75,101.000000,0.0,0.0,1.0,0.0,0.0,64.0
76,101.000000,1.0,1.0,0.0,0.0,0.0,14.0
77,103.000000,1.0,1.0,0.0,1.0,0.0,70.0
78,100.000000,0.0,0.0,0.0,1.0,0.0,19.0


In [43]:
X_tested = transformer.transform(X_test)

In [44]:
df_tested = pd.DataFrame(X_tested, columns=transformed_columns)
df_tested

,fever,cough_encoded,gender_Male,city_Delhi,city_Kolkata,city_Mumbai,age
0,101.000000,0.0,1.0,1.0,0.0,0.0,42.0
1,98.000000,0.0,1.0,0.0,1.0,0.0,24.0
2,101.000000,0.0,0.0,1.0,0.0,0.0,49.0
3,99.000000,1.0,1.0,0.0,0.0,0.0,66.0
4,101.000000,0.0,1.0,1.0,0.0,0.0,19.0
5,104.000000,0.0,1.0,0.0,0.0,1.0,44.0
6,104.000000,0.0,1.0,0.0,1.0,0.0,51.0
7,102.000000,0.0,1.0,0.0,1.0,0.0,5.0
8,99.000000,0.0,0.0,0.0,0.0,0.0,22.0
9,100.680556,0.0,1.0,1.0,0.0,0.0,38.0
